spring.application.name=appointment-service

server.port=8083

resilience4j.circuitbreaker.instances.doctorServiceCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.doctorServiceCB.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.doctorServiceCB.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.doctorServiceCB.permitted-number-of-calls-in-half-open-state=3

logging.level.io.github.resilience4j=DEBUG

# ===============================
# Resilience4j Retry
# ===============================

resilience4j.retry.instances.patientRetry.max-attempts=3
resilience4j.retry.instances.patientRetry.wait-duration=2s
resilience4j.retry.instances.patientRetry.retry-exceptions=org.springframework.web.client.ResourceAccessException

# Hiển thị log Retry nếu cần debug
logging.level.io.github.resilience4j.retry=DEBUG

# ===============================
# Rate Limiter
# ===============================
resilience4j.ratelimiter.instances.searchDoctorLimit.limit-for-period=5
resilience4j.ratelimiter.instances.searchDoctorLimit.limit-refresh-period=10s
resilience4j.ratelimiter.instances.searchDoctorLimit.timeout-duration=0s